version: '3.8'

services:
  # 1. DATABASE (MySQL)
  db_jbmotor:
    image: mysql:8.0
    container_name: db_jbmotor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jb_network
    # Cek kesehatan DB (Biar App gak buru-buru jalan sebelum DB siap)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. BACKEND (Node.js App)
  app_jbmotor:
    build: ./app
    container_name: app_jbmotor
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=3000
    depends_on:
      db_jbmotor:
        condition: service_healthy
    volumes:
      # [JURUS KUNCI 1] Mapping folder UPLOAD (Biar gambar gak ilang pas restart)
      - ./app/public/uploads:/usr/src/app/public/uploads

      # [JURUS KUNCI 2] Mapping KODINGAN (Biar update HTML/JS langsung berubah)
      - ./app:/usr/src/app

      # [PENGAMAN] Folder node_modules jangan di-override dari laptop
      - /usr/src/app/node_modules
    networks:
      - jb_network

  # 3. WEBSERVER (Nginx)
  nginx_jbmotor:
    image: nginx:alpine
    container_name: nginx_jbmotor
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_jbmotor
    networks:
      - jb_network

volumes:
  mysql_data:

networks:
  jb_network:
    driver: bridge